erDiagram
    COCTAIL ||--o{ COCTAIL-INGREDIENT: ""
    COCTAIL-INGREDIENT }o--|| INGREDIENT: ""

    COCTAIL {
        bigint id PK
        string name "NOT NULL"
        string category "NOT NULL"
        string instructions
    }
    COCTAIL-INGREDIENT {
        bigint cocktail_id PK, FK
        bigint ingredient_id PK, FK
        string quantity "NOT NULL"
    }
    INGREDIENT {
        bigint id PK
        string name "NOT NULL"
        string description
        boolean alcohol "NOT NULL"
        string image_url
    }
