openapi: 3.0.3
info:
  title: Cocktails API
  version: 0.1.0
tags:
  - name: Auth
    description: Everything about security
paths:
  /login:
    post:
      tags:
        - Auth
      summary: Login and obtain the token
      description: Allows you to login and obtain the token that will be used for authentication and authorization in further app usage.
      operationId: login
      requestBody:
        description: user credentials
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  type:
                    type: string
                    example: "bearer"
                  value:
                    type: string
                    example: "token"
        '400':
          description: Failure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
  /register:
    post:
      tags:
        - Auth
      summary: Register into the system
      description: Allows you to register
      operationId: register
      requestBody:
        description: user credentials
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '204':
          description: Successful registration
        '422':
          description: Failure
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
components:
  schemas:
    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: "#/components/schemas/Error"
    Error:
      type: object
      properties:
        message:
          type: string
          example: "Invalid user credentials"
